{
 "title": "Nvidia GPU",
 "description": "Contains GPU related statistics.",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "avg Temp.",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL" }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "avg GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)" }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "avg Encoder Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_ENC_UTIL)" }
   ]
  },
  {
   "title": "Encoder Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_ENC_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "avg Decoder Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_DEC_UTIL)" }
   ]
  },
  {
   "title": "Decoder Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_DEC_UTIL", "legendFormat": "{{modelName}}" }
   ]
  }
 ]
}