{
 "title": "PSU Overview",
 "tags": [
  "hardware",
  "PSU"
 ],
 "time": { "from": "2022-03-14T09:52:56.193Z", "to": "2022-03-14T23:46:31.857Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Input Power",
   "type": "timeseries",
   "description": "Estimated PSU input power.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "liquidctl_hidraw4_estimated_input_power{}"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "description": "Estimated PSU output power.",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "liquidctl_hidraw4_total_power_output{}"
    }
   ]
  },
  {
   "title": "Temp 1",
   "type": "gauge",
   "description": "PSU temperature sensor 1.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw4_temperature_1{}"
    }
   ]
  },
  {
   "title": "Temp 2",
   "type": "gauge",
   "description": "Second PSU temperature sensor.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw4_temperature_2{}"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw4_estimated_efficiency{}"
    }
   ]
  },
  {
   "title": "avg Temp.",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(temperature_gpu)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_gpu", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_used/memory_total" }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "memory_used/memory_total", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "avg GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(utilization_gpu)" }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "utilization_gpu", "legendFormat": "{{gpu}}" }
   ]
  }
 ]
}