{
 "title": "Power Usage",
 "description": "Visualize TP-Link Smart Plug Kasa metrics",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kasa_online)" }
   ]
  },
  {
   "title": "Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kasa_online==1)" }
   ]
  },
  {
   "title": "Device with Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kasa_relay_state==1)" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 11, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "kasa_relay_state", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Power Current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kasa_power_load)" },
    {}
   ]
  },
  {
   "title": "Power Max last 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    { "expr": "sum(kasa_power_load)", "legendFormat": "Max Power" }
   ]
  },
  {
   "title": "Total Power Current Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(kasa_power_load[1y])) /240 /1000"
    }
   ]
  },
  {
   "title": "Watts per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kasa_power_load[1h]) /240",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(kasa_power_load[24h])) /240 /1000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Power Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "sum(kasa_power_load)", "legendFormat": "Total" },
    { "expr": "kasa_power_load", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "sum(kasa_current)", "legendFormat": "Total" },
    { "expr": "kasa_current", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(kasa_power_total[24h])",
     "legendFormat": "{{alias}}"
    },
    { "expr": "increase(kasa_power_total[7d])", "legendFormat": "{{alias}}" },
    {
     "expr": "increase(kasa_power_total[30d])",
     "legendFormat": "{{alias}}"
    },
    { "expr": "increase(kasa_power_total[1y])", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "High Power Loads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "kasa_power_load{alias=~\"APC Rack|Hifi|PC|Büro|Kühlschrank|Waschmaschine|Spülmaschine|Küchenzeile\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 38 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "kasa_voltage", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Low Power Loads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "kasa_power_load{alias=~\"APC Hifi|Couch|Drucker|Kamera Flur|Kamera Wohnzimmer|APC Router\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 48 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "kasa_rssi", "legendFormat": "{{alias}}" }
   ]
  }
 ]
}