{
 "title": "GPU Overview",
 "description": "Contains GPU related statistics.",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temp.",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_GPU_TEMP)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_GPU_TEMP)",
     "legendFormat": "{{modelName}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_MEM_COPY_UTIL)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_MEM_COPY_UTIL)",
     "legendFormat": "{{modelName}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "{{modelName}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "Encoder Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_ENC_UTIL)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Encoder Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_ENC_UTIL)",
     "legendFormat": "{{modelName}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "Decoder Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_DEC_UTIL)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Decoder Utilization / Card",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (modelName, device, gpu) (DCGM_FI_DEV_DEC_UTIL)",
     "legendFormat": "{{modelName}} - {{gpu}}"
    }
   ]
  }
 ]
}