{
 "title": "Livepeer Payments Overview",
 "description": "Contains LivePeer Payment statistics.",
 "tags": [
  "livepeer",
  "payments",
  "orchestrator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "energy_price", "label": "Energy Price", "query": "0.4" }
  ]
 },
 "panels": [
  { "title": "Expense", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Price", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "All (cost)", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Year (cost)", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Month (cost)", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Week (cost)", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "Day (cost)", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "Payout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Expected Payout in ETH",
   "type": "stat",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "timeseries",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Tickets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(livepeer_tickets_recv)" },
    {
     "expr": "increase(livepeer_tickets_recv[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_payment_recv_errors)"
    }
   ]
  },
  {
   "title": "Value Redeemed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_value_redeemed" }
   ]
  },
  {
   "title": "Ticket Redemption Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_ticket_redemption_errors"
    }
   ]
  },
  {
   "title": "# Winning Tickets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "# Winning Tickets" }
   ],
   "targets": [
    { "expr": "livepeer_winning_tickets_recv" }
   ]
  },
  {
   "title": "Transcoding Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "livepeer_transcoding_price" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "livepeer_suggested_gas_price" }
   ]
  }
 ]
}