{
 "title": "Orchestrator Overview",
 "description": "Contains statistics about the LivePeer orchestrator.",
 "tags": [
  "livepeer",
  "orchestrator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Orch Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active",
   "type": "stat",
   "description": "Whether the orchestrator is currently active",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# Delegators",
   "type": "stat",
   "description": "Number of delegators that are currently staked with the orchestrator",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_delegator_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Price Per Unit",
   "type": "stat",
   "description": "The price per unit in the orchestrator charges",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_transcoding_price)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Claimed Fees",
   "type": "stat",
   "description": "Total receved fees",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_total_volume_eth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fee Value",
   "type": "stat",
   "description": "Total value of the received fees",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Fee Cut",
   "type": "stat",
   "description": "Orchestrator fee cut",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_fee_cut", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "bargauge",
   "description": "Orchestrator stream success rate",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_success_rate", "legendFormat": "{{region}}" }
   ]
  },
  {
   "title": "Round Trip Score",
   "type": "bargauge",
   "description": "Orchestrator round trip score",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_round_trip_score", "legendFormat": "{{region}}" }
   ]
  },
  {
   "title": "Score",
   "type": "bargauge",
   "description": "Total orchestrator score",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_total_score", "legendFormat": "{{region}}" }
   ]
  },
  {
   "title": "# Rounds Active",
   "type": "stat",
   "description": "Number of rounds the orchestrator has been active",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_orch_current_round - livepeer_orch_activation_round",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Ratio",
   "type": "stat",
   "description": "Orchestrator reward call ratio over the latest 30 rounds",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_orch_thirty_day_reward_claim_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "stat",
   "description": "Total LPT staked to the orchestrator",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LPT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_total_stake", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Reward",
   "type": "stat",
   "description": "Total claimed LPT rewards",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LPT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_orch_total_claimed_rewards",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Reward Value",
   "type": "stat",
   "description": "Total value of claimed LPT rewards",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Reward Cut",
   "type": "stat",
   "description": "Orchestrator reward cut",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_reward_cut", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "👑 Delegators",
   "type": "table",
   "description": "Delegators that are currently staking with the orchestrator.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "livepeer_orch_delegator_bonded_amount",
     "legendFormat": "bonded amound"
    },
    {
     "expr": "livepeer_orch_delegator_start_round",
     "legendFormat": "start round"
    }
   ]
  },
  {
   "title": "💎 Claimed Rewards",
   "type": "table",
   "description": "The rewards claimed by the orchestrator.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "livepeer_orch_reward_amount", "legendFormat": "bonded amound" },
    {
     "expr": "livepeer_orch_reward_block_time",
     "legendFormat": "start round"
    }
   ]
  },
  {
   "title": "🎟️ Winning Tickets",
   "type": "table",
   "description": "The winning tickets received by the orchestrator.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "livepeer_orch_winning_ticket_amount",
     "legendFormat": "bonded amound"
    },
    {
     "expr": "livepeer_orch_winning_ticket_block_time",
     "legendFormat": "start round"
    }
   ]
  },
  { "title": "Orch Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Daily Projected Income in ETH",
   "type": "stat",
   "description": "Based on data from the previous 24h",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[1d])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "stat",
   "description": "The expected payout when a ticket is won",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(sum(increase(livepeer_ticket_value_recv[10y]))-(sum(increase(livepeer_value_redeemed[10y])) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Transcoders",
   "type": "stat",
   "description": "The total number of transcoders connected to the orchestrator",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_transcoders_number)+sum(livepeer_versions{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Orchestrator Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"}) * 100"
    }
   ]
  },
  {
   "title": "# Orchestrators Sessions (Continuous)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(avg_over_time(livepeer_current_sessions_total{node_type=\"orch\"}[1h]))",
     "legendFormat": "Hourly Avg"
    }
   ]
  },
  {
   "title": "# Orchestrator Sessions (Current)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Transcode Score (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(livepeer_transcode_score_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_score_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Score (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Transcode Times (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{profiles}}"
    }
   ]
  },
  {
   "title": "Transcode Times (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Source Duration (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(livepeer_source_segment_duration_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_source_segment_duration_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_source_segment_duration_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Download Times (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(livepeer_download_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_download_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Times (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_download_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Test Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate",
     "type": "barchart",
     "description": "Orchestrator test stream transcode success rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "livepeer_orch_test_stream_success_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Round Trip Time",
     "type": "barchart",
     "description": "Orchestrator test stream round trip time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "livepeer_orch_test_stream_round_trip_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download Time",
     "type": "barchart",
     "description": "Orchestrator test stream segment download time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "livepeer_orch_test_stream_download_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload Time",
     "type": "barchart",
     "description": "Orchestrator test stream segment upload time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "livepeer_orch_test_stream_upload_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transcode Time",
     "type": "barchart",
     "description": "Orchestrator test stream segment transcode time",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "livepeer_orch_test_stream_transcode_time",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}