{
 "title": "Orchestrator Payments Overview",
 "description": "Contains orchestrator LivePeer Payment statistics.",
 "tags": [
  "livepeer",
  "payments",
  "orchestrator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Income", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH Price",
   "type": "stat",
   "description": "Current ETH price",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ETH_price{currency=\"EUR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fees",
   "type": "stat",
   "description": "Total received ETH fees",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ticket_value_recv[5y])) / 10^9"
    }
   ]
  },
  {
   "title": "Fee Income (all)",
   "type": "stat",
   "description": "All time fee income",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Fee Income (year)",
   "type": "stat",
   "description": "Fee income of the last year",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Fee Income (month)",
   "type": "stat",
   "description": "Fee income of the last month",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Fee Income (week)",
   "type": "stat",
   "description": "Fee income of the last week",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Fee Income (day)",
   "type": "stat",
   "description": "Fee income of the last day",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "LPT Price",
   "type": "stat",
   "description": "Current LPT price",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "LPT_price{currency=\"EUR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Reward",
   "type": "stat",
   "description": "Total received LPT rewards",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LPT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_total_rewards", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Reward Value",
   "type": "stat",
   "description": "Total value of claimed LPT rewards",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy Price",
     "type": "stat",
     "description": "The local energy price",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "0.37690", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Energy Cost (all)",
     "type": "stat",
     "description": "All time energy consumption cost",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[5y:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) * 0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Energy Cost (year)",
     "type": "stat",
     "description": "All time energy consumption cost",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[5y:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) * 0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Energy Cost (quarter)",
     "type": "stat",
     "description": "Energy cost of the last quarter",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[90d:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) * 0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Energy Cost (month)",
     "type": "stat",
     "description": "Energy cost of the last month",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[30d:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) * 0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Energy Cost (week)",
     "type": "stat",
     "description": "Energy cost of the last week",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[7d:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) * 0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Energy Cost (day)",
     "type": "stat",
     "description": "Energy cost of the last day",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(sum(liquidctl_estimated_input_power)[1d:]) / count_over_time(sum(liquidctl_estimated_input_power)[1h:]) / 1000) *  0.37690",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mean Gas Price",
     "type": "stat",
     "description": "The mean gas price",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Gwei" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(livepeer_orch_winning_ticket_gas_price)/10^9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gas Cost (all)",
     "type": "stat",
     "description": "The total gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Cost (year)",
     "type": "stat",
     "description": "The annual gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Cost (quater)",
     "type": "stat",
     "description": "The quaterly gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Cost (month)",
     "type": "stat",
     "description": "The monthly gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Cost (week)",
     "type": "stat",
     "description": "The weekly gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Cost (day)",
     "type": "stat",
     "description": "The daily gas cost for claiming rewards and redeeming tickets",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Paid",
     "type": "timeseries",
     "description": "The total amount of gas paid by the orchestrator for claiming rewards and redeeming winning tickets",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "((livepeer_orch_tickets_total_gas_cost+livepeer_orch_rewards_total_gas_cost)/10^9)*0.85",
       "legendFormat": "ETH"
      },
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Paid (rewards)",
     "type": "timeseries",
     "description": "The total amount of gas paid by the orchestrator for claiming rewards",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "(livepeer_orch_rewards_total_gas_cost/10^9)*0.85",
       "legendFormat": "ETH"
      },
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    },
    {
     "title": "Gas Paid (tickets)",
     "type": "timeseries",
     "description": "The total amount of gas paid by the orchestrator for redeeming winning tickets",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "(livepeer_orch_tickets_total_gas_cost/10^9)*0.85",
       "legendFormat": "ETH"
      },
      { "expression": "${Gas Cost}*${ETH Price}", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Orchestrator Profit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "LPT Share",
     "type": "stat",
     "description": "The amount of staked LPT that is bonded by the orchestrator",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(livepeer_orch_stake/livepeer_orch_total_stake)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fee Cut",
     "type": "stat",
     "description": "Orchestrator fee cut",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "livepeer_orch_fee_cut", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Fee Profit (all)",
     "type": "stat",
     "description": "The total fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Fee Profit (year)",
     "type": "stat",
     "description": "The yearly fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Fee Profit (quarter)",
     "type": "stat",
     "description": "The quarterly fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Fee Profit (month)",
     "type": "stat",
     "description": "The monthly fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Fee Profit (week)",
     "type": "stat",
     "description": "The weekly fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Fee Profit (day)",
     "type": "stat",
     "description": "The daily fee allocated to the orchestrator, derived from a calculation involving the orchestrator's fee profit, fee cut, contributed stake, as well as the associated energy and gas costs.",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(($fee_value - $fee_value_orch_cut)*$orch_lpt_share+$fee_value_orch_cut)-$energy_cost-$gas_cost_euro",
       "type": "math"
      }
     ]
    },
    {
     "title": "Reward Cut",
     "type": "stat",
     "description": "Orchestrator reward cut",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "livepeer_orch_reward_cut", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Rewards Profit (all)",
     "type": "stat",
     "description": "The total rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Rewards Profit (year)",
     "type": "stat",
     "description": "The yearly rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Rewards Profit (quarter)",
     "type": "stat",
     "description": "The quarterly rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Rewards Profit (month)",
     "type": "stat",
     "description": "The monthly rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Rewards Profit (week)",
     "type": "stat",
     "description": "The weekly rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Rewards Profit (day)",
     "type": "stat",
     "description": "The daily rewards allocated to the orchestrator, calculated from the orchestrator's reward cut and their contributed stake.",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($rewards_value-$rewards_value_orch_cut)*$orch_lpt_share+($rewards_value_orch_cut-$gas_cost_euro)",
       "type": "math"
      }
     ]
    }
   ]
  },
  { "title": "Payout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Tickets Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Tickets Received",
   "type": "stat",
   "description": "The tickets that were received since a ticket was won.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Received - ($Needed*$Won)", "type": "math" }
   ]
  },
  {
   "title": "Total Claimed Fees",
   "type": "stat",
   "description": "Total claimed fees",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livepeer_orch_total_volume_eth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Expected Payout",
   "type": "stat",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(livepeer_ticket_value_recv[10y]))-(sum(increase(livepeer_value_redeemed[10y])) OR on() vector(0)))/10^9 -0.012"
    }
   ]
  },
  {
   "title": "Expected Payout in ETH",
   "type": "timeseries",
   "description": "Ticket Value received minus ticket value redeemed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(livepeer_ticket_value_recv[10y]))-(sum(increase(livepeer_value_redeemed[10y])) OR on() vector(0)))/10^9"
    }
   ]
  },
  {
   "title": "# Tickets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_tickets_recv[10y]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "stat",
   "description": "Short-term sentiment of the orchestrator and delegators based on the expected luck. ",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($Expected-$Actual)/0.012", "type": "math" }
   ]
  },
  {
   "title": "Expected Luck",
   "type": "stat",
   "description": "The orchestrator's likelihood of winning a new ticket based on how many fees are overdue",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($Expected-$Actual)/0.012", "type": "math" }
   ]
  },
  {
   "title": "Total Claimed Fee Value",
   "type": "stat",
   "description": "Total value of the claimed fees",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Expected Payout in EURO",
   "type": "stat",
   "description": "Ticket Value received minus ticket value redeemed times the ETH price",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_payment_recv_errors[100y]))"
    }
   ]
  },
  {
   "title": "Value Redeemed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "livepeer_value_redeemed" }
   ]
  },
  {
   "title": "Ticket Redemption Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_ticket_redemption_errors"
    }
   ]
  },
  {
   "title": "# Winning Tickets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(livepeer_winning_tickets_recv[5y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transcoding Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(livepeer_transcoding_price)"
    }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(livepeer_suggested_gas_price)"
    }
   ]
  }
 ]
}