{
 "title": "PSU Overview",
 "description": "Contains PSU related statistics.",
 "tags": [
  "hardware",
  "PSU"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "energy_price", "label": "Energy Price", "query": "0.4" }
  ]
 },
 "panels": [
  { "title": "Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price",
   "type": "stat",
   "description": "The local energy price.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$energy_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Day",
   "type": "stat",
   "description": "Energy consumption of last day.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(liquidctl_hidraw1_estimated_input_power[24h]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Week",
   "type": "stat",
   "description": "Energy consumption of the last week.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(liquidctl_hidraw1_estimated_input_power[7d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Month",
   "type": "stat",
   "description": "Energy consumption of the last month.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(liquidctl_hidraw1_estimated_input_power[30d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "description": "Energy consumption of the last Year.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(liquidctl_hidraw1_estimated_input_power[365d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All",
   "type": "stat",
   "description": "All time energy consumption.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(liquidctl_hidraw1_estimated_input_power[10y]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Day (cost)",
   "type": "stat",
   "description": "Energy cost of the last day.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(liquidctl_hidraw1_estimated_input_power[24h]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000) * $energy_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Week (cost)",
   "type": "stat",
   "description": "Energy cost of the last week.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(liquidctl_hidraw1_estimated_input_power[7d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000) * $energy_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Month (cost)",
   "type": "stat",
   "description": "Energy cost of the last month.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(liquidctl_hidraw1_estimated_input_power[30d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000) * $energy_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Year (cost)",
   "type": "stat",
   "description": "Energy cost of the last Year.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(liquidctl_hidraw1_estimated_input_power[365d]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000) * $energy_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All (cost)",
   "type": "stat",
   "description": "All time energy consumption cost.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(liquidctl_hidraw1_estimated_input_power[15y]) / (count_over_time(scrape_samples_scraped[1m]) * 60) / 1000) * $energy_price",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PSU stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Input Power",
   "type": "timeseries",
   "description": "Estimated PSU input power.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "liquidctl_hidraw1_estimated_input_power{}",
     "legendFormat": "signal"
    },
    {
     "expr": "avg_over_time(liquidctl_hidraw1_estimated_input_power[1d])",
     "legendFormat": "MA (1d)"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "description": "Estimated PSU output power.",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "liquidctl_hidraw1_total_power_output{}",
     "legendFormat": "signal"
    },
    {
     "expr": "avg_over_time(liquidctl_hidraw1_total_power_output[1d])",
     "legendFormat": "MA (1d)"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "PSU temperature sensor",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw1_vrm_temperature{}"
    }
   ]
  },
  {
   "title": "Case Temp",
   "type": "gauge",
   "description": "PSU case temperature sensor.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw1_case_temperature{}"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "liquidctl_hidraw1_estimated_efficiency{}"
    }
   ]
  },
  {
   "title": "Hourly Power by Device",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(liquidctl_hidraw1_estimated_input_power[60m])*0.001",
     "legendFormat": "kWh"
    }
   ]
  },
  {
   "title": "Power spikes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(liquidctl_hidraw1_estimated_input_power[60m])",
     "legendFormat": "Rate of Power"
    }
   ]
  }
 ]
}