version: "3.8"

name: livepeer-orchestrator

services:
  livepeer-combined-orchestrator:
    image: livepeer/go-livepeer:master
    container_name: "livepeer-combined-orchestrator"
    restart: unless-stopped
    runtime: nvidia
    ports:
      # - 7936:7935 # Make CLI server available on host.
      - 8935:8935
    volumes:
      - ./config/lporch.cfg:/root/lporch.cfg
      - lpdata:/root/.lpData
    command: ["-config", "/root/lporch.cfg", "-ethPassword", "/run/secrets/eth_password"]
    secrets:
      - eth_password

volumes:
  lpdata:

networks:
  default:
    name: livepeer
    external: true

secrets:
  eth_password:
    file: ./.eth_password.txt
